- build
  - test
  - quality

default:
  image: maven:3.8.1-jdk-11

cache:
  paths:
    - .m2/repository
  key: "$CI_JOB_NAME"


build_job:
  inherit:
    default: true
    variables: true
  stage: build
  script:
    - mvn compile


test_job:
  inherit:
    default: true
    variables: true
  stage: test
  script:
    - mvn test